export const LANG = {
  hi: {
    // Nav
    nav_today: 'Aaj', nav_orders: 'Order', nav_khata: 'Khata',
    nav_expenses: 'Kharcha', nav_menu: 'Menu',
    // Common
    loading: 'Load ho raha hai...', save: 'Save Karein', cancel: 'Cancel',
    error_save: 'Save nahi hua', error_amount: 'Sahi amount dalein',
    // Dashboard
    dash_title: 'Aaj Ka Hisab', total_sales: 'Total Bikri',
    orders_today: 'order aaj', cash: 'Cash', upi: 'UPI',
    credit: 'Khata (Credit)', expenses_label: 'Aaj ka Kharcha',
    cash_in_hand: 'Cash haath mein', total_due: 'Total Udhaar Bakaya',
    open_orders: 'Khule Order', dash_error: 'Aaj ka hisab load nahi ho saka',
    // Orders
    orders_title: 'Aaj Ke Order', new_order: '+ Naya Order',
    no_orders: 'Aaj abhi koi order nahi hai',
    // Order Detail
    bill_heading: 'Bill banayein — payment mode chunein',
    pay_error_phone: 'Khata ke liye customer ka phone number is order mein nahi hai',
    pay_error: 'Payment save nahi hua',
    walkin: 'Walk-in customer',
    // Khata
    khata_title: 'Khata Bahi', total_credit_due: 'Total udhaar bakaya',
    no_khata: 'Koi khata entry nahi hai', settle_btn: 'Payment Liya — Settle Karein',
    whatsapp_remind: 'WhatsApp pe yaad dilayein',
    settle_error: 'Settle nahi hua', confirm: 'Confirm',
    // Expenses
    exp_title: 'Aaj Ka Kharcha', exp_total: 'Total kharcha aaj',
    add_expense: '+ Kharcha Add Karein', no_expenses: 'Aaj abhi koi kharcha nahi likha',
    exp_mode_label: 'Kharcha hua:', exp_cash: 'Cash', exp_upi: 'UPI',
    // Menu
    menu_title: 'Menu', add_item: '+ Menu Item Add Karein',
    item_name: 'Item ka naam', item_category: 'Category (jaise Starter, Main, Bread)',
    no_menu: 'Abhi koi menu item nahi hai', remove: 'Hatayein',
    menu_error: 'Naam aur price zaroori hai', logout: 'Logout',
    // Login
    login_sub: 'Apna register, ab digital', owner_login: 'Malik Login',
    staff_login: 'Staff Login', login_btn: 'Login karein',
    find_staff: 'Aage badhein', searching: 'Dhoond rahe hain...',
    new_rest: 'Naya restaurant?', create_account: 'Account banayein',
    choose_name: 'apna naam chunein', enter_pin: 'apna PIN dalein', back: '← Wapas',
    login_error: 'Login nahi ho saka, dobara try karein',
    phone_error: 'Number nahi mila', pin_error: 'PIN galat hai',
    // Register
    reg_title: 'Naya Khata Kholein', reg_sub: '2 minute mein shuru karein',
    reg_rest_name: 'Restaurant ka naam', reg_owner_name: 'Aapka naam',
    reg_password: 'Password banayein', reg_btn: 'Khata shuru karein',
    reg_creating: 'Ban raha hai...', reg_existing: 'Pehle se account hai?',
    reg_login: 'Login karein', reg_error: 'Account nahi ban saka, dobara try karein',
    // NewOrder
    new_order_title: 'Naya Order', cart_empty: 'Pehle kuch items select karein',
    credit_phone_req: 'Khata ke liye customer ka phone number zaroori hai',
    order_error: 'Order save nahi hua, dobara try karein',
    save_open: 'Order Save Karein (Baad mein bill)', bill_cash: 'Bill - Cash',
    bill_upi: 'Bill - UPI', bill_credit: 'Bill - Khata',
    table_no: 'Table no. (optional)', cust_name: 'Customer naam (optional)',
    cust_phone: 'Phone (Khata ke liye zaroori)',
  },
  en: {
    nav_today: 'Today', nav_orders: 'Orders', nav_khata: 'Ledger',
    nav_expenses: 'Expenses', nav_menu: 'Menu',
    loading: 'Loading...', save: 'Save', cancel: 'Cancel',
    error_save: 'Could not save', error_amount: 'Enter a valid amount',
    dash_title: "Today's Summary", total_sales: 'Total Sales',
    orders_today: 'orders today', cash: 'Cash', upi: 'UPI',
    credit: 'Credit (Khata)', expenses_label: "Today's Expenses",
    cash_in_hand: 'Net Cash in Hand', total_due: 'Total Credit Due',
    open_orders: 'Open Orders', dash_error: "Could not load today's summary",
    orders_title: "Today's Orders", new_order: '+ New Order',
    no_orders: 'No orders today',
    bill_heading: 'Create Bill — choose payment mode',
    pay_error_phone: 'Customer phone not found on this order for credit',
    pay_error: 'Could not save payment',
    walkin: 'Walk-in customer',
    khata_title: 'Credit Ledger', total_credit_due: 'Total credit due',
    no_khata: 'No credit entries yet', settle_btn: 'Payment Received — Settle',
    whatsapp_remind: 'Send WhatsApp Reminder',
    settle_error: 'Could not settle', confirm: 'Confirm',
    exp_title: "Today's Expenses", exp_total: 'Total expenses today',
    add_expense: '+ Add Expense', no_expenses: 'No expenses recorded today',
    exp_mode_label: 'Paid via:', exp_cash: 'Cash', exp_upi: 'UPI',
    menu_title: 'Menu', add_item: '+ Add Menu Item',
    item_name: 'Item name', item_category: 'Category (e.g. Starter, Main, Bread)',
    no_menu: 'No menu items yet', remove: 'Remove',
    menu_error: 'Name and price are required', logout: 'Logout',
    login_sub: 'Your register, now digital', owner_login: 'Owner Login',
    staff_login: 'Staff Login', login_btn: 'Login',
    find_staff: 'Continue', searching: 'Searching...',
    new_rest: 'New restaurant?', create_account: 'Create account',
    choose_name: 'choose your name', enter_pin: 'enter your PIN', back: '← Back',
    login_error: 'Login failed, please try again',
    phone_error: 'Number not found', pin_error: 'Incorrect PIN',
    reg_title: 'Create New Account', reg_sub: 'Get started in 2 minutes',
    reg_rest_name: 'Restaurant name', reg_owner_name: 'Your name',
    reg_password: 'Create a password', reg_btn: 'Create Account',
    reg_creating: 'Creating...', reg_existing: 'Already have an account?',
    reg_login: 'Login', reg_error: 'Could not create account, please try again',
    new_order_title: 'New Order', cart_empty: 'Please select at least one item',
    credit_phone_req: 'Customer phone is required for credit orders',
    order_error: 'Could not save order, please try again',
    save_open: 'Save Order (Bill Later)', bill_cash: 'Bill - Cash',
    bill_upi: 'Bill - UPI', bill_credit: 'Bill - Credit',
    table_no: 'Table no. (optional)', cust_name: 'Customer name (optional)',
    cust_phone: 'Phone (required for credit)',
  },
};
